### ISSUE TITLE
docker login

### ISSUE THREAD

**Issue by ivwsai** [EonYang/doodle-classification-server#6]
Error response from daemon: pull access denied for doodle-classify-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by EonYang** [comment]
You got this error message because the image is not on the Docker Hub. 

I don't plan to put this repo on Docker Hub, because the code was super messy and it was written almost 2 years ago and the project is discontinued

I'll create a docker-compose file to make it easier and write proper documentation soon.

**Comment by t111** [comment]
Please check out the latest repo and run `docker-compose up`.

To test it out, please follow the latest `README.md`.
